In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3,4])
type(a)
a.shape
print(a)

[1 2 3 4]


In [13]:
a=np.array([[1],[2],[3],[4]])
type(a)
a.shape
print(a)
a.shape
#4rows 1 column

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [16]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#there is also one way to put any no in array
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#generating random matrux
Matrix=np.random.random((2,3))
Matrix

array([[0.43794949, 0.25405474, 0.6772983 ],
       [0.83588096, 0.91531098, 0.82794504]])

In [32]:
#What if i want to excess value of 1 column
Matrix[:,1]

array([0.25405474, 0.91531098])

In [35]:
# Now i want to change the values of row 1 
Matrix[1,0:3]=1

In [36]:
Matrix

array([[0.43794949, 0.25405474, 0.6772983 ],
       [1.        , 1.        , 1.        ]])

In [42]:
#Mathematical Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [43]:
#dot product
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [50]:
#Sum Fucntion
print(np.sum(x))
np.sum(x,axis=0)

10


array([4, 6])

In [57]:
#Stacking of array Function means adding array in one stack
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
b=b**2
#Now i want to add these array into one stack
stack=np.stack((a,b),axis=0)

In [60]:
#Now i want to reshape My array:
#Now my array is 4 rows 2 columns
stack.reshape((4,2))

array([[ 1,  2],
       [ 3,  4],
       [25, 36],
       [49, 64]])