In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3,4])
type(a)
a.shape
print(a)

[1 2 3 4]


In [13]:
a=np.array([[1],[2],[3],[4]])
type(a)
a.shape
print(a)
a.shape
#4rows 1 column

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [16]:
a=np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#there is also one way to put any no in array
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#generating random matrux
Matrix=np.random.random((2,3))
Matrix

array([[0.43794949, 0.25405474, 0.6772983 ],
       [0.83588096, 0.91531098, 0.82794504]])

In [32]:
#What if i want to excess value of 1 column
Matrix[:,1]

array([0.25405474, 0.91531098])

In [35]:
# Now i want to change the values of row 1 
Matrix[1,0:3]=1

In [36]:
Matrix

array([[0.43794949, 0.25405474, 0.6772983 ],
       [1.        , 1.        , 1.        ]])

In [42]:
#Mathematical Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [43]:
#dot product
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [50]:
#Sum Fucntion
print(np.sum(x))
np.sum(x,axis=0)

10


array([4, 6])

In [57]:
#Stacking of array Function means adding array in one stack
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
b=b**2
#Now i want to add these array into one stack
stack=np.stack((a,b),axis=0)

In [60]:
#Now i want to reshape My array:
#Now my array is 4 rows 2 columns
stack.reshape((4,2))

array([[ 1,  2],
       [ 3,  4],
       [25, 36],
       [49, 64]])

# Numpy Random Module

In [64]:
a=np.arange(10)+5
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
import random
#Suppose i want to suffle the array randomly
np.random.shuffle(a)
a

array([ 8, 10, 11,  9, 14,  5,  7, 12, 13,  6])

In [71]:
#Standard Normal distrubution values using random function or you can say that it generating values randomly if you dont known normal dist
np.random.randn(2,3)

array([[-1.3511635 , -0.69975304,  0.12105392],
       [-0.5875524 , -0.33273374,  0.05111039]])

In [77]:
#what if i want n no between the range randomly
print(np.random.randint(5,10,3))#5,10 is range and last no is the values you want 
print(np.random.randint(5,10,4))

[7 9 5]
[6 9 6 7]


In [78]:
# what if i want to choose randomly
np.random.choice([1,4,2,3,6,8])

3

In [100]:
#if you want to replicate or you want that my random no will be same you use seed
np.random.seed(1)
a=np.random.randint(5,10,3)
a

array([8, 9, 5])

# Statistical Functions

In [116]:
#Here axis is usefull in multi dimensional array if you want to compare column wise like 1 to 5 2 to 6 and so on 
#you use axis=0 and if yow want to find min from both array then axi=1
a=np.array([[1,2,3,4],[5,6,7,8]])
np.min((a),axis=1)

array([1, 5])

In [120]:
#Mean same as above but now using mean
np.mean((a),axis=0)

array([3., 4., 5., 6.])

In [122]:
c=np.array([1,4,5,7])
np.median(c)

4.5

In [125]:
#Weighted mean a statistical concept to prevent the effect of outliers
w=np.array([1,2,3,4])
np.average(c,weights=w)

5.2

In [130]:
#Standard deviation
c=[4,7,3,1,3,9,76]
#what if i dont want to use std function
u=np.mean(c)
std=np.sqrt(np.mean(abs(c-u)**2))
print(std)
#Or you can use in built function
print(np.std(c))
# for variance we all know that std is a sqrt of variance
np.var(c)


25.14366881806736
25.14366881806736


632.2040816326529